/*
 * Copyright (C) 2015 Vincenzo Abate <gogolander@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package unipd.astro;

import java.awt.Color;
import java.awt.Component;
import java.io.BufferedReader;
import java.io.File;
import javax.swing.filechooser.FileFilter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vincenzo Abate <gogolander@gmail.com>
 */
public class Main extends javax.swing.JPanel {

    private int selectedAction = 0;
    private boolean conflicts = false;
    private ImageList imageList;
    private String basePath;
    private ImageList list_obj;
    private ImageList list_lamp;
    private ImageList wlcalList;
    private ImageList fcalList;
    private ImageList backgroundList;
    private ImageList apallList;
    private ImageList imcopyList;
    private ImageList scombineList;
    private String irafPath = "";

    /**
     * Creates new form Main
     */
    public Main() {
        BufferedReader irafPathRead;
        try {
            irafPathRead = new BufferedReader(new FileReader(System.getProperty("user.home") + File.separator + ".irafPath"));
            try {
                this.irafPath = irafPathRead.readLine();
                if (irafPath == null) {
                    JFileChooser fileChooser = new JFileChooser(System.getProperty("user.home"));
                    fileChooser.setFileFilter(new FileFilter() {
                        @Override
                        public boolean accept(File pathname) {
                            return (pathname.getName().equals("login.cl") || pathname.isDirectory());
                        }

                        @Override
                        public String getDescription() {
                            return "Select the login.cl generated by the command \"mkiraf\"";
                        }
                    });

                    if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                        PrintWriter write = new PrintWriter(new FileWriter(System.getProperty("user.home") + File.separator + ".irafPath"));
                        write.print(fileChooser.getSelectedFile().getParent());
                        write.close();
                    }
                }
            } catch (Exception ex) {
                Logger.getLogger(Main.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
                JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (FileNotFoundException ex) {
            JFileChooser fileChooser = new JFileChooser(System.getProperty("user.home"));
            fileChooser.setFileFilter(new FileFilter() {
                @Override
                public boolean accept(File pathname) {
                    return (pathname.getName().equals("login.cl") || pathname.isDirectory());
                }

                @Override
                public String getDescription() {
                    return "Select the login.cl generated by the command \"mkiraf\"";
                }
            });

            if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
                PrintWriter write = null;
                try {
                    write = new PrintWriter(new FileWriter(System.getProperty("user.home") + File.separator + ".irafPath"));
                    write.print(fileChooser.getSelectedFile().getParent());
                    write.close();
                } catch (IOException ex1) {
                    write.close();
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, ex1.getMessage(), ex1);
                    JOptionPane.showMessageDialog(this, ex1.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        initComponents();

        this.jTable1.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int col) {
                /**
                 * Color legend: 1. standards: HSV=217,100,100; RGB=0,96,255 2.
                 * objects: HSV=130,92,100; RGB=20,255,59 3. lamps:
                 * HSV=55,75,100; RGB=255,239,64 4. conflicts: HSV=37,100,100;
                 * RGB=255,156,0 5. flat: HSV=55,15,100; RGB=255,252,216
                 */
                float[] hsv = new float[3];
                if (imageList != null && imageList.size() > 0) {
                    Image image = imageList.get(row);
                    this.setForeground(Color.BLACK);
                    //Lamps
                    if (image.getType().equals("LAMP"))
                        hsv = Color.RGBtoHSB(255, 243, 115, hsv);
                    //Conflicts
                    else if (image.getType().equals("IMAGE") && (image.getLampName().isEmpty() || image.getStandardName().isEmpty())) {
                        hsv = Color.RGBtoHSB(255, 54, 0, hsv);
                        this.setForeground(Color.WHITE);
                    } //Objects and standards
                    else if (image.getType().equals("IMAGE") && !image.getLampName().isEmpty() && !image.getStandardName().isEmpty()) {
                        if (image.isStandard()) {
                            hsv = Color.RGBtoHSB(102, 161, 255, hsv);
                        } else {
                            hsv = Color.RGBtoHSB(20, 255, 59, hsv);
                        }
                    } //Flatfield
                    else if (image.getType().equals("FLATFIELD")) {
                        hsv = Color.RGBtoHSB(255, 252, 216, hsv);
                    }

                    setBackground(Color.getHSBColor(hsv[0], hsv[1], hsv[2]));
                }
                super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, col);
                return this;
            }
        });
        this.jTable1.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(new JComboBox(new String[]{"IMAGE", "FLATFIELD", "LAMP"})));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupAction = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jSolve = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPath = new javax.swing.JTextField();
        jExplore = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLoad = new javax.swing.JButton();
        jNext = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPrevious = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jRadioListsOnly = new javax.swing.JRadioButton();
        jRadioListsAndOneScript = new javax.swing.JRadioButton();
        jRadioListsAndMultipleScripts = new javax.swing.JRadioButton();
        jRadioAllAndExec = new javax.swing.JRadioButton();
        jDoIt = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("STEP 2"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, "", null}
            },
            new String [] {
                "Image name", "Target name", "Type", "Is standard?", "Exp Time", "Lamp", "Standard"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setShowVerticalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jTable1PropertyChange(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Image");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Type");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Is standard?");
            jTable1.getColumnModel().getColumn(4).setHeaderValue("Exp Time");
            jTable1.getColumnModel().getColumn(5).setHeaderValue("Lamp");
            jTable1.getColumnModel().getColumn(6).setHeaderValue("Standard");
        }

        jLabel2.setText("Verify the data association and correct all conflicts:");

        jLabel4.setText("Color legend:");

        jLabel5.setBackground(new java.awt.Color(255, 251, 216));
        jLabel5.setText("FLATFIELD");

        jLabel6.setBackground(new java.awt.Color(255, 243, 114));
        jLabel6.setText("LAMP");

        jLabel7.setBackground(new java.awt.Color(101, 160, 255));
        jLabel7.setText("STANDARD");

        jLabel8.setBackground(new java.awt.Color(20, 255, 59));
        jLabel8.setText("OBJECT");

        jLabel9.setBackground(new java.awt.Color(255, 157, 0));
        jLabel9.setText("CONFLICT");

        jPanel6.setBackground(new java.awt.Color(255, 251, 216));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setPreferredSize(new java.awt.Dimension(14, 14));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(255, 243, 114));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setPreferredSize(new java.awt.Dimension(14, 14));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel9.setBackground(new java.awt.Color(101, 160, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setPreferredSize(new java.awt.Dimension(14, 14));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel10.setBackground(new java.awt.Color(255, 54, 0));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setPreferredSize(new java.awt.Dimension(14, 14));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(20, 255, 59));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setPreferredSize(new java.awt.Dimension(14, 14));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jSolve.setText("Try to resolve conflicts");
        jSolve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSolveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jSolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel5))
                                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6))
                                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSolve, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("STEP 1"));

        jExplore.setText("Explore");
        jExplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jExploreActionPerformed(evt);
            }
        });

        jLabel1.setText("Select the directory witch contains the images you want to reduce:");

        jLoad.setText("Load data");
        jLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPath)
                        .addGap(18, 18, 18)
                        .addComponent(jExplore))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLoad)
                .addGap(377, 377, 377))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPath)
                    .addComponent(jExplore))
                .addGap(18, 18, 18)
                .addComponent(jLoad)
                .addGap(12, 12, 12))
        );

        jNext.setText("Next");
        jNext.setEnabled(false);
        jNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jNext)
                .addGap(232, 232, 232))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jNext)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data input", jPanel3);

        jPrevious.setText("Back");
        jPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPreviousActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("STEP 3"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Boolean(true), null,  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true),  new Boolean(true)}
            },
            new String [] {
                "Enabled", "Target", "prered2", "wlcal", "flcal", "background", "apall", "scombine", "imcopy"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.String.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setShowVerticalLines(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jLabel3.setText("Set what task to apply to images:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("STEP 4"));

        groupAction.add(jRadioListsOnly);
        jRadioListsOnly.setSelected(true);
        jRadioListsOnly.setText("Generate only lists to be used within IRAF");
        jRadioListsOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioListsOnlyActionPerformed(evt);
            }
        });

        groupAction.add(jRadioListsAndOneScript);
        jRadioListsAndOneScript.setText("Geneare lists and only one PyRAF script for all objects");
        jRadioListsAndOneScript.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioListsAndOneScriptActionPerformed(evt);
            }
        });

        groupAction.add(jRadioListsAndMultipleScripts);
        jRadioListsAndMultipleScripts.setText("Generate lists and one PyRAF script per object");
        jRadioListsAndMultipleScripts.setEnabled(false);
        jRadioListsAndMultipleScripts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioListsAndMultipleScriptsActionPerformed(evt);
            }
        });

        groupAction.add(jRadioAllAndExec);
        jRadioAllAndExec.setText("Generate lists, one PyRAF script and execute it");
        jRadioAllAndExec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAllAndExecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioListsOnly)
                    .addComponent(jRadioListsAndOneScript)
                    .addComponent(jRadioAllAndExec)
                    .addComponent(jRadioListsAndMultipleScripts))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioListsOnly)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioListsAndOneScript)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioListsAndMultipleScripts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioAllAndExec)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jDoIt.setText("Do it");
        jDoIt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDoItActionPerformed(evt);
            }
        });

        jLabel10.setText("Select what you want to obtain:");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDoIt, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel10))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jDoIt, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPrevious)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jPrevious)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data lists and Python scripts generation", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jTable1PropertyChange
        int x = this.jTable1.getSelectedRow();
        int y = this.jTable1.getSelectedColumn();
        switch (y) {
            case 2:
                this.imageList.get(x).setType((String) this.jTable1.getValueAt(x, y));
                break;
            case 3:
                this.imageList.get(x).setIsStandard((Boolean) this.jTable1.getValueAt(x, y));
                break;
            case 5:
                this.imageList.get(x).setLampName((String) this.jTable1.getValueAt(x, y));
                break;
            case 6:
                this.imageList.get(x).setStandardName((String) this.jTable1.getValueAt(x, y));
        }
    }//GEN-LAST:event_jTable1PropertyChange

    private void jExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jExploreActionPerformed
        JFileChooser fileChooser = new JFileChooser(System.getProperty("user.home"));
        fileChooser.setFileFilter(new FileFilter() {
            @Override
            public boolean accept(File pathname) {
                return (pathname.getName().equals("fits_list") || pathname.isDirectory());
            }

            @Override
            public String getDescription() {
                return "Select fits_list generated by imhead";
            }
        });

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            this.basePath = fileChooser.getSelectedFile().getParent();
            this.jPath.setText(fileChooser.getSelectedFile().getAbsolutePath());
        }
    }//GEN-LAST:event_jExploreActionPerformed

    private void jLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoadActionPerformed
        try {
            if (this.jPath.getText().startsWith("file://")) {
                this.jPath.setText(this.jPath.getText().replace("file://", "").trim());
                this.basePath = this.jPath.getText().replace("fits_list", "");
            }

            parseFile(this.jPath.getText());
            imageList.fixLamps();
            imageList.fixStandards();
            this.updateImagesTable();
            this.jNext.setEnabled(true);
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jLoadActionPerformed

    private void jNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNextActionPerformed
        this.jTabbedPane1.setEnabled(true);
        this.jTabbedPane1.setSelectedIndex(1);
        updateTasksTable();
    }//GEN-LAST:event_jNextActionPerformed

    private void jPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPreviousActionPerformed
        this.jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_jPreviousActionPerformed

    private void jSolveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSolveActionPerformed
        this.imageList.fixLamps();
        this.imageList.fixStandards();
        this.updateImagesTable();
    }//GEN-LAST:event_jSolveActionPerformed

    private void jRadioListsOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioListsOnlyActionPerformed
        this.selectedAction = 0;
    }//GEN-LAST:event_jRadioListsOnlyActionPerformed

    private void jRadioListsAndOneScriptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioListsAndOneScriptActionPerformed
        this.selectedAction = 1;
    }//GEN-LAST:event_jRadioListsAndOneScriptActionPerformed

    private void jRadioListsAndMultipleScriptsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioListsAndMultipleScriptsActionPerformed
        this.selectedAction = 2;
    }//GEN-LAST:event_jRadioListsAndMultipleScriptsActionPerformed

    private void jRadioAllAndExecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAllAndExecActionPerformed
        this.selectedAction = 3;
    }//GEN-LAST:event_jRadioAllAndExecActionPerformed

    private void jDoItActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDoItActionPerformed
        try {
            this.generateAllLists();
            switch (this.selectedAction) {
                case 0:
                    Logger.getLogger(Main.class.getName()).log(Level.INFO, "Lists created.");
                    JOptionPane.showMessageDialog(this, "Lists have been created correctly.", "All done", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 1:
                    this.writeOneGiantScript();
                    Logger.getLogger(Main.class.getName()).log(Level.INFO, "Lists and one script created.");
                    JOptionPane.showMessageDialog(this, "Lists and the PyRAF script have been created correctly.", "All done", JOptionPane.INFORMATION_MESSAGE);
                    break;
                case 2:
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, "Unauthorized access to option \"Create lists and one script for each object\"");
                    JOptionPane.showMessageDialog(this, "Not implemented yet! How did you get here?!", "Nothing done", JOptionPane.WARNING_MESSAGE);
                    break;
                case 3:
                    this.writeOneGiantScript();
                    Process p = Runtime.getRuntime().exec("python " + this.basePath + File.separator + "execAsgred.py");

                    while (p.isAlive()) {
                        if (p.getInputStream().available() != 0) {
                            while (p.getInputStream().available() != 0) {
                                byte[] character = new byte[1];
                                p.getInputStream().read(character);
                                System.out.print(character);
                            }
                        }
                    }

                    if (p.getErrorStream().available() != 0) {
                        byte[] buffer = new byte[p.getErrorStream().available()];
                        p.getErrorStream().read(buffer);
                        System.out.print(new String(buffer));
                    }
                    Logger.getLogger(Main.class.getName()).log(Level.INFO, "Lists and one script created. The script was executed.");
                    JOptionPane.showMessageDialog(this, "Lists and the PyRAF script have been created correctly. The script was executed.", "All done", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jDoItActionPerformed

    public void parseFile(String filePath) throws FileNotFoundException, IOException {
        String line = "";
        imageList = new ImageList();
        BufferedReader fitsList = new BufferedReader(new FileReader(filePath));
        do {
            line = fitsList.readLine();
            //Ignore comments, empty lines and EOF
            if (line != null && !line.startsWith("#") && !line.equals("")) {
                imageList.add(Image.parseImage(line));
            }
        } while (line != null);
        fitsList.close();
    }

    public void updateImagesTable() {
        if (imageList == null || imageList.size() == 0) {
            return;
        }

        // Prepare the list of standard stars
        ArrayList<String> listStds = new ArrayList<>();
        for (Image image : imageList.getStandards()) {
            listStds.add(image.getFileName());
        }
        JComboBox comboStd = new JComboBox(listStds.toArray());

        // Prepare the list of lamps
        ArrayList<String> listLamps = new ArrayList<>();
        for (Image image : imageList.getLamps()) {
            listLamps.add(image.getFileName());
        }
        JComboBox lamps = new JComboBox(listLamps.toArray());

        this.jTable1.getColumnModel().getColumn(5).setCellEditor(new DefaultCellEditor(lamps));
        this.jTable1.getColumnModel().getColumn(6).setCellEditor(new DefaultCellEditor(comboStd));

        if (((DefaultTableModel) this.jTable1.getModel()).getRowCount() > 0) {
            for (int i = ((DefaultTableModel) this.jTable1.getModel()).getRowCount() - 1; i > -1; i--) {
                ((DefaultTableModel) this.jTable1.getModel()).removeRow(i);
            }
        }

        for (Image image : imageList) {
            ((DefaultTableModel) this.jTable1.getModel()).addRow(new Object[]{
                image.getFileName(), image.getTargetName(), image.getType(), image.isStandard(),
                image.getExpTime(), image.getLampName(), image.getStandardName()});
        }
    }

    public void updateTasksTable() {
        if (imageList == null || imageList.size() == 0) {
            return;
        }

        if (((DefaultTableModel) this.jTable2.getModel()).getRowCount() > 0) {
            for (int i = ((DefaultTableModel) this.jTable2.getModel()).getRowCount() - 1; i > -1; i--) {
                ((DefaultTableModel) this.jTable2.getModel()).removeRow(i);
            }
        }

        for (String target : imageList.generateTargetsList()) {
            ((DefaultTableModel) this.jTable2.getModel()).addRow(new Object[]{
                true, target, true, true, true, true, true, true, true});
        }
    }

    public void generateAllLists() {
        PrintWriter writer = null;
        try {
            list_obj = new ImageList();
            list_lamp = new ImageList();
            wlcalList = new ImageList();
            fcalList = new ImageList();
            backgroundList = new ImageList();
            apallList = new ImageList();

            //Generate lists to write
            for (int i = 0; i < this.jTable2.getModel().getRowCount(); i++) {
                if ((boolean) this.jTable2.getModel().getValueAt(i, 0)) {
                    //Get all images for the target
                    for (Image image : this.imageList.getImagesWhoseTargetIs((String) this.jTable2.getModel().getValueAt(i, 1))) {
                        //Apply prered2?
                        if ((boolean) this.jTable2.getModel().getValueAt(i, 2)) {
                            list_obj.add(image);
                            if (!list_lamp.contains(imageList.getImageWhoseFileNameIs(image.getLampName()))) {
                                list_lamp.add(imageList.getImageWhoseFileNameIs(image.getLampName()));
                            }
                        }
                        //Apply wlcal?
                        if ((boolean) this.jTable2.getModel().getValueAt(i, 3)) {
                            wlcalList.add(image);
                        }
                        //Apply fcal?
                        if ((boolean) this.jTable2.getModel().getValueAt(i, 4)) {
                            fcalList.add(image);
                        }
                        //Apply background?
                        if ((boolean) this.jTable2.getModel().getValueAt(i, 5)) {
                            backgroundList.add(image);
                        }
                        //Apply apall?
                        if ((boolean) this.jTable2.getModel().getValueAt(i, 6)) {
                            apallList.add(image);
                        }
                    }
                }
            }
            String temp = "";
            //Write them down
            writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "list_obj"));
            for (Image image : list_obj) {
                temp += image.getFileName() + "\t" + image.getLampName() + "\n";
            }
            writer.print(temp.trim());
            writer.close();
            temp = "";
            writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "list_lamps"));
            for (Image image : list_lamp) {
                temp += image.getFileName() + "\n";
            }
            writer.print(temp.trim());
            writer.close();
            writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "list_flat"));
            writer.print(imageList.generateFlatList());
            writer.close();

            // Generate the list of IMA*.wl.fits
            for (String target : wlcalList.generateTargetsList()) {
                temp = target;
                if (target.contains("+")) {
                    temp = temp.replaceAll("+", "p");
                }
                if (target.contains("-")) {
                    temp = temp.replaceAll("-", "m");
                }
                writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "wl" + temp));
                temp = "";
                for (String imageName : wlcalList.getImagesFileNameWhoseTargetIs(target)) {
                    temp += wlcalList.appendExtension(imageName, "wl") + "\n";
                }
                writer.print(temp.trim());
                writer.close();
            }

            // Generate the list of IMA*.fc.fits
            // This list is used as input for the background task
            for (String target : fcalList.generateTargetsList()) {
                temp = target;
                if (target.contains("+")) {
                    temp = temp.replaceAll("+", "p");
                }
                if (target.contains("-")) {
                    temp = temp.replaceAll("-", "m");
                }
                writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "fc" + temp));
                temp = "";
                for (String imageName : fcalList.getImagesFileNameWhoseTargetIs(target)) {
                    temp += fcalList.appendExtension(imageName, "fc") + "\n";
                }
                writer.print(temp.trim());
                writer.close();
            }

            // Generate the list of IMA*.bg.fits
            for (String target : backgroundList.generateTargetsList()) {
                temp = target;
                if (target.contains("+")) {
                    temp = temp.replaceAll("+", "p");
                }
                if (target.contains("-")) {
                    temp = temp.replaceAll("-", "m");
                }
                writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "bg" + temp));
                temp = "";
                for (String imageName : backgroundList.getImagesFileNameWhoseTargetIs(target)) {
                    temp += backgroundList.appendExtension(imageName, "bg") + "\n";
                }
                writer.print(temp.trim());
                writer.close();
            }

            // Generate the list of IMA*.md.fits
            for (String target : apallList.generateTargetsList()) {
                temp = target;
                if (target.contains("+")) {
                    temp = temp.replaceAll("+", "p");
                }
                if (target.contains("-")) {
                    temp = temp.replaceAll("-", "m");
                }
                writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "md" + temp));
                temp = "";
                for (String imageName : apallList.getImagesFileNameWhoseTargetIs(target)) {
                    temp += apallList.appendExtension(imageName, "md") + "\n";
                }
                writer.print(temp.trim());
                writer.close();
            }

            // Generate the list of IMA*.fc.fits
            // This list is used as input for standard parameter of fcal task
            for (Image standard : fcalList.getStandards()) {
                // Use file name instead of standard name to avoid confusion: the
                // same standard used twice during the night MUST be treated as two
                // different stars
                temp = "";
                writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "std" + standard.getFileName()));
                for (Image imageName : fcalList.getImagesWhoseStandardIs(standard.getFileName())) {
                    temp += fcalList.appendExtension(imageName.getFileName(), "fc") + "\n";
                }
                writer.print(temp.trim());
                writer.close();
            }
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (writer != null) {
            writer.close();
        }
    }

    public void writeOneGiantScript() {
        PrintWriter writer = null;
        try {
            // Let's generate the PyRAF script
            writer = new PrintWriter(new FileWriter(this.basePath + File.separator + "execAsgred.py"));
            writer.println("#!/usr/bin/env python");
            writer.println("import os");
            writer.println("os.chdir(\"" + this.irafPath + "\")");
            writer.println("import sys");
            writer.println("from pyraf import iraf");
            writer.println("iraf.epar(\"display\")");
            // exec prered2
            writer.println("iraf.asgred.prered2(flat=\"list_flat\", comp=\"list_lamps\", object=\"list_obj\", order=11)");
            // exec wlcal
            writer.println("iraf.asgred.wlcal(input=\"list_obj\", refer=\"" + imageList.getFirstLamp() + "\")");
            // exec fcal
            if (fcalList != null) {
                for (Image standard : fcalList.getStandards()) {
                    writer.println("iraf.asgred.fcal(obj=\"std" + standard.getFileName() + "\",stand=\"" + standard.getFileName() + "\", dir=\"onedstds$" + Image.standardList.getCatalogue(standard.getTargetName()) + "\")");
                }
            }

            // exec background
            if (backgroundList != null) {
                for (String target : backgroundList.generateTargetsList()) {
                    String temp = target;
                    if (target.contains("+")) {
                        temp = target.replaceAll("+", "p");
                    }
                    if (temp.contains("-")) {
                        temp = temp.replaceAll("-", "m");
                    }
                    writer.println("iraf.asgred.background(input=\"@fc" + temp + "\",output=\"@bg" + temp + "\")");
                }
            }
            // exec apall
            if (apallList != null) {
                for (String target : apallList.generateTargetsList()) {
                    String temp = target;
                    if (target.contains("+")) {
                        temp = target.replaceAll("+", "p");
                    }
                    if (temp.contains("-")) {
                        temp = temp.replaceAll("-", "m");
                    }
                    writer.println("iraf.asgred.apall(input=\"@bg" + temp + "\", output=\"@md" + temp + "\")");
                }
            }
            // exec scombine
            if (scombineList != null) {
                for (String target : scombineList.generateTargetsList()) {
                    String temp = target;
                    if (target.contains("+")) {
                        temp = target.replaceAll("+", "p");
                    }
                    if (temp.contains("-")) {
                        temp = temp.replaceAll("-", "m");
                    }
                    writer.println("iraf.asgred.scombine(input=\"@md" + temp + "\",output=\"" + temp + ".md\")");
                }
            }
            // exec imcopy
            if (imcopyList != null) {
                for (String target : imcopyList.generateTargetsList()) {
                    String temp = target;
                    if (target.contains("+")) {
                        temp = target.replaceAll("+", "p");
                    }
                    if (temp.contains("-")) {
                        temp = temp.replaceAll("-", "m");
                    }
                    writer.println("iraf.asgred.imcopy(input=\"" + temp + ".md[50:2048]\",output=\"" + temp + ".obj\")");
                }
            }
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, ex.getMessage(), ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
        if (writer != null) {
            writer.close();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup groupAction;
    private javax.swing.JButton jDoIt;
    private javax.swing.JButton jExplore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jLoad;
    private javax.swing.JButton jNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jPath;
    private javax.swing.JButton jPrevious;
    private javax.swing.JRadioButton jRadioAllAndExec;
    private javax.swing.JRadioButton jRadioListsAndMultipleScripts;
    private javax.swing.JRadioButton jRadioListsAndOneScript;
    private javax.swing.JRadioButton jRadioListsOnly;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jSolve;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
